### PR TITLE
translate readme to english

### PR DESCRIPTION
**Pull request by yuankunzhang**
Translate README.md to English.

### CODE REVIEW

**Comment by chenjiandongx** [comment]
@yuankunzhang Thanks for your contributions. Could you give me your wechat id or email? 😄

**Comment by chenjiandongx** [comment]
I'm looking for someone to maintain this project together.

**Comment by yuankunzhang** [comment]
Sure, my Wechat ID: ZmViZXIwMDcK

**Comment by chenjiandongx** [comment]
em...., Wechat say your id is not exist, lol...

**Comment by chenjiandongx** [comment]
my wechat id: chenjiandongx

**Pull request merged**
